"""Framework-neutral note domain, persistence, migration, and services."""

from .command_service import NoteCommandService
from .commands import (
    BatchUpdateTagsCommand,
    CreateNoteCommand,
    HardDeleteCommand,
    NoteValidationError,
    RestoreCommand,
    SetPinnedCommand,
    SoftDeleteCommand,
    UpdateNoteCommand,
)
from .database_executor import DatabaseExecutor, DatabaseExecutorClosedError
from .domain import Note, NoteSource
from .migration import (
    DataPreparationError,
    DatabaseInspection,
    DatabaseValidationError,
    LegacyCandidate,
    LegacySchemaError,
    MigrationConflictError,
    MigrationResult,
    TagFileValidationError,
    discover_legacy_database_candidates,
    discover_legacy_tag_candidates,
    inspect_database,
    prepare_gate1_local_data,
    read_tag_file,
)
from .query_service import NoteQueryService
from .repository import (
    NoteNotFoundError,
    NoteRepository,
    NoteRepositoryError,
    NoteStateError,
)
from .service_errors import (
    NoteServiceError,
    NoteServiceNotFoundError,
    NoteServiceRepositoryError,
    NoteServiceStateError,
    NoteServiceUnavailableError,
)
from .sqlalchemy_repository import (
    SqlAlchemyNoteRepository,
    create_session_factory,
    create_sqlite_engine,
    initialize_database,
)
from .tag_catalog import (
    DEFAULT_TAGS,
    PROTECTED_TAGS,
    SYSTEM_CATEGORY_NAMES,
    TagCatalog,
    TagCatalogError,
    TagCatalogFormatError,
    TagCatalogItem,
    TagInUseError,
    TagValidationError,
)
from .tag_catalog_service import TagCatalogService, TagDeleteInspection

__all__ = [
    "BatchUpdateTagsCommand",
    "CreateNoteCommand",
    "DEFAULT_TAGS",
    "DataPreparationError",
    "DatabaseExecutor",
    "DatabaseExecutorClosedError",
    "DatabaseInspection",
    "DatabaseValidationError",
    "HardDeleteCommand",
    "LegacyCandidate",
    "LegacySchemaError",
    "MigrationConflictError",
    "MigrationResult",
    "Note",
    "NoteCommandService",
    "NoteNotFoundError",
    "NoteQueryService",
    "NoteRepository",
    "NoteRepositoryError",
    "NoteServiceError",
    "NoteServiceNotFoundError",
    "NoteServiceRepositoryError",
    "NoteServiceStateError",
    "NoteServiceUnavailableError",
    "NoteSource",
    "NoteStateError",
    "NoteValidationError",
    "PROTECTED_TAGS",
    "RestoreCommand",
    "SYSTEM_CATEGORY_NAMES",
    "SetPinnedCommand",
    "SoftDeleteCommand",
    "SqlAlchemyNoteRepository",
    "TagCatalog",
    "TagCatalogError",
    "TagCatalogFormatError",
    "TagCatalogItem",
    "TagCatalogService",
    "TagDeleteInspection",
    "TagFileValidationError",
    "TagInUseError",
    "TagValidationError",
    "UpdateNoteCommand",
    "create_session_factory",
    "create_sqlite_engine",
    "discover_legacy_database_candidates",
    "discover_legacy_tag_candidates",
    "initialize_database",
    "inspect_database",
    "prepare_gate1_local_data",
    "read_tag_file",
]
