"""Shared Gate 3 audio runtime and Gate 6 framework-neutral contracts."""

from .engine import (
    AssistantAudioEngine,
    AudioEngineBusyError,
    AudioEngineFailure,
    AudioEngineGenerationError,
    MicrophoneLeaseCoordinator,
)
from .barge_in import AcousticBargeInCoordinator, AcousticBargeInSnapshot
from .fake_audio import (
    AudioCaptureBusyError,
    AudioCaptureGenerationError,
    FakeCaptureScript,
    FakeOpusEncoder,
    ScriptedFakeAudioCapture,
    ScriptedVoiceActivityDetector,
)
from .gate6_contracts import (
    AudioDeviceDescriptor,
    AudioDeviceRegistryPort,
    AudioDeviceSnapshot,
    AudioPlatform,
    AudioProcessingMetrics,
    AudioProcessingPort,
    AudioRouteEvent,
    AudioRouteObserverPort,
    AudioRouteState,
    CaptureActivity,
    DeviceDirection,
    DevicePreference,
    DevicePreferenceMode,
    DuplexAudioPlan,
    DuplexAudioSessionPort,
    DuplexCallbacks,
    KeywordSpotResult,
    KeywordSpotterPort,
    MicrophoneOwner,
    PlaybackActivity,
    ProcessedPcmFrame,
    ProcessingState,
    PublicAudioFormat,
    ResolvedAudioRoute,
    RouteEventKind,
    TimedPcmFrame,
)
from .models import (
    DEFAULT_BYTES_PER_FRAME,
    DEFAULT_CHANNELS,
    DEFAULT_FRAME_DURATION_MS,
    DEFAULT_OPUS_BITRATE_BPS,
    DEFAULT_SAMPLE_RATE_HZ,
    DEFAULT_SAMPLES_PER_FRAME,
    ENCODED_PACKET_CAPACITY,
    PCM_INGRESS_CAPACITY,
    AudioCaptureSummary,
    EncodedAudioPacket,
    PcmFrame,
    VoiceActivitySnapshot,
)
from .kws_model_registry import (
    DEFAULT_KWS_MODEL_DIRECTORY,
    DEFAULT_KWS_WAKE_PHRASE,
    KwsModelFiles,
    KwsModelRegistry,
    KwsModelSnapshot,
)
from .offline_kws import (
    LocalKwsCaptureRuntime,
    OfflineKwsCoordinator,
    OfflineKwsSnapshot,
)
from .opus_codec import OpusUnavailableError, PyAvOpusEncoder
from .ports import (
    AudioCapturePort,
    AudioClock,
    OpusEncoderPort,
    VoiceActivityDetectorPort,
)
from .pyaudio_adapter import PyAudioCaptureAdapter, PyAudioUnavailableError
from .queues import (
    AudioQueueClosed,
    AudioQueueOverflow,
    AudioQueueStats,
    DropOldestAudioQueue,
    FailOnOverflowAudioQueue,
)
from .vad import EnergyVadConfig, EnergyVoiceActivityDetector

__all__ = [
    "AssistantAudioEngine",
    "AcousticBargeInCoordinator",
    "AcousticBargeInSnapshot",
    "AudioCaptureBusyError",
    "AudioCaptureGenerationError",
    "AudioCapturePort",
    "AudioCaptureSummary",
    "AudioClock",
    "AudioDeviceDescriptor",
    "AudioDeviceRegistryPort",
    "AudioDeviceSnapshot",
    "AudioEngineBusyError",
    "AudioEngineFailure",
    "AudioEngineGenerationError",
    "AudioPlatform",
    "AudioProcessingMetrics",
    "AudioProcessingPort",
    "AudioQueueClosed",
    "AudioQueueOverflow",
    "AudioQueueStats",
    "AudioRouteEvent",
    "AudioRouteObserverPort",
    "AudioRouteState",
    "CaptureActivity",
    "DEFAULT_BYTES_PER_FRAME",
    "DEFAULT_CHANNELS",
    "DEFAULT_FRAME_DURATION_MS",
    "DEFAULT_OPUS_BITRATE_BPS",
    "DEFAULT_SAMPLE_RATE_HZ",
    "DEFAULT_SAMPLES_PER_FRAME",
    "DeviceDirection",
    "DevicePreference",
    "DevicePreferenceMode",
    "DropOldestAudioQueue",
    "DuplexAudioPlan",
    "DuplexAudioSessionPort",
    "DuplexCallbacks",
    "ENCODED_PACKET_CAPACITY",
    "EncodedAudioPacket",
    "EnergyVadConfig",
    "EnergyVoiceActivityDetector",
    "FailOnOverflowAudioQueue",
    "FakeCaptureScript",
    "FakeOpusEncoder",
    "KeywordSpotResult",
    "KeywordSpotterPort",
    "KwsModelFiles",
    "KwsModelRegistry",
    "KwsModelSnapshot",
    "LocalKwsCaptureRuntime",
    "MicrophoneLeaseCoordinator",
    "MicrophoneOwner",
    "OfflineKwsCoordinator",
    "OfflineKwsSnapshot",
    "OpusEncoderPort",
    "OpusUnavailableError",
    "PCM_INGRESS_CAPACITY",
    "PcmFrame",
    "PlaybackActivity",
    "ProcessedPcmFrame",
    "ProcessingState",
    "PublicAudioFormat",
    "PyAudioCaptureAdapter",
    "PyAudioUnavailableError",
    "PyAvOpusEncoder",
    "ResolvedAudioRoute",
    "RouteEventKind",
    "ScriptedFakeAudioCapture",
    "ScriptedVoiceActivityDetector",
    "TimedPcmFrame",
    "VoiceActivityDetectorPort",
    "VoiceActivitySnapshot",
    "DEFAULT_KWS_MODEL_DIRECTORY",
    "DEFAULT_KWS_WAKE_PHRASE",
]
